### ISSUE TITLE
[BUG]: Suggested terms should not be empty

### ISSUE THREAD

**Issue by YohannParis** [DARPA-ASKEM/TERArium#529] opened 2023-01-24 19:11 UTC
**Describe the bug**
When suggested terms returns an empty list, do not display the suggested terms.

**Screenshots**
<img width="1242" alt="Screen Shot 2023-01-24 at 14 10 09" src="https://user-images.githubusercontent.com/636801/214386171-b6393763-2401-465d-9bfd-e390d9bce2ee.png">

**Comment by echl** [comment] 2023-01-26 19:43
Closing for now, cannot reproduce

**Closed by echl** 2023-01-26 19:43 UTC
Labels: bug, Front End/HMI
