### ISSUE TITLE
Calibration vegalite warning

### ISSUE THREAD

**Issue by Tom-Szendrey** [DARPA-ASKEM/terarium#5331] opened 2024-10-29 19:04 UTC
Running a calibration you can often find the following vegalite warning
We should look into this when we get the chance

Details:
Steps to reproduce:
I ran the default configuration of the following model with a sample size of 1 for 100 timesteps.
I then hooked the same config up to a calibration with the simulation's dataset.
This is a meaningless calibration but it allows us to easily reproduce this warning

Model: [Test SIR Model.json](https://github.com/user-attachments/files/17561926/Test.SIR.Model.json)

WARN Infinite extent for field "timepoint_id": [Infinity, -Infinity] 

![Image](https://github.com/user-attachments/assets/8336571b-60bc-40c3-bae3-22d79de65623)
![Image](https://github.com/user-attachments/assets/8c3e9588-4c6c-47f7-89f4-e0ebb67594db)

**Comment by mwdchang** [comment] 2024-11-14 21:10
A lot of these warnings are addressed in https://github.com/DARPA-ASKEM/terarium/pull/5476, the cause is insertion of empty layers with no usable data.

**Closed by mwdchang** 2024-11-14 21:10 UTC
