### ISSUE TITLE
[BUG]: Terarium fails to properly handle CSV files with commas in their headers

### ISSUE THREAD

**Issue by dgauldie** [DARPA-ASKEM/terarium#4970] opened 2024-09-27 19:48 UTC
**Describe the bug**
Bug report From John Wenskovitch (PNNL):  I'm loading in a CSV dataset in which some of the columns have a comma in the header (e.g., "South System Flows to DITP, MGD").  When I open the dataset, this is correctly interpreted as a single column in the Data section at the bottom, but it is interpreted as two separate columns above in the Column Information section.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by dvince2** [comment] 2024-10-07 18:30
Closing this issue as a duplicate of #4994

**Closed by dvince2** 2024-10-07 18:30 UTC
Labels: bug
