### ISSUE TITLE
[BUG]: Clicking `Save for reuse` in `Create model from equations` operator does not consistently set the output node to what's saved

### ISSUE THREAD

**Issue by liunelson** [DARPA-ASKEM/terarium#5062] opened 2024-10-04 15:44 UTC
**Describe the bug**

Bug 1: `Save for reuse` does not seem to consistently assign the saved model onto the output node

Bug 2: Configurations created for the output node model (`Output - 3`) and those created for the model from `Save for reuse` are not same.

https://app.staging.terarium.ai/projects/34e7b955-f408-4e8b-be27-9429480ad6aa/workflow/f9eeb338-ff79-4f30-845b-cd5efe979cad

**To Reproduce**
1. Paste these equations into `Create model from equations`
```
\frac{d S}{d t} = -\sigma \beta S I \frac{1-\alpha}{N} - \alpha S
\frac{d E}{d t} = \sigma \beta S I \frac{1-\alpha}{N}- \gamma E
\frac{d I}{d t} = \gamma E - \nu I
\frac{d H}{d t} = \nu I - \delta_{1} H - \delta_{2} H
\frac{d R}{d t} = \delta_{1} H
\frac{d D}{d t} = \delta_{2} H
\frac{d V}{d t} = \alpha S
```
2. Click `Run`
3. Click `Save for reuse` and use the name `SEIHRDV`
4. Notice that the output node flashes briefly to `SEIHRDV` and changes back to `Output - 3`
5. Connect the output node named `Output - 3` to a `Configure model` operator and create some configuration `test 1`
6. Drop and drop the `SEIHRDV` model on the canvas and create a configuration `test 2` for it
7. Notice that `test 1` does not appear in the list of configurations of `SEIHRDV`, ditto for `test 2` in `Output - 3`'s list of configurations.

**Expected Behaviour**

If Bug 1 does not occur (i.e. the output node is consistently assigned to whatever is "saved for reuse"), then Bug 2 is irrelevant.
It's unclear what `Output - 3` is - is it meant to be placeholder  or alias of whatever is saved? If the latter, then they should point to the same list of configurations. If the former, then Bug 1 is the main issue.

**Screenshots**
![Image](https://github.com/user-attachments/assets/dcccc2d6-67fb-462f-9966-8bc66cbed333)

**Comment by blanchco** [comment] 2024-10-25 16:34
This bug was opened quite a while ago and I am not able to reproduce this.  Is this still relevant @liunelson ?

**Comment by blanchco** [comment] 2024-10-25 19:18
Closing as this is no longer relevant

**Closed by blanchco** 2024-10-25 19:18 UTC
Labels: bug
