### ISSUE TITLE
[FEAT]: Ability to Run simulation from the Simulation Plan page

### ISSUE THREAD

**Issue by dgauldie** [DARPA-ASKEM/TERArium#148] opened 2022-10-28 19:22 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by dvince2** [comment] 2023-01-31 19:28
This appears to be a duplicate of #149

**Closed by dvince2** 2023-01-31 19:28 UTC
Labels: feature
